core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("sms.urls")),
    path("admin/", admin.site.urls),
]

sms/urls.py
from django.urls import path

from . import views

app_name = "sms"

urlpatterns = [
    # LIST
    path("", views.RollView.as_view(), name="list_student"),
    path("dashboard/", views.RollView.as_view(), name="dashboard"),
    path("courses/", views.CourseView.as_view(), name="list_course"),
    path("subjects/", views.SubjectView.as_view(), name="list_subject"),
    path("section/", views.SectionView.as_view(), name="list_section"),
    path("classrooms/", views.ClassroomView.as_view(), name="list_classroom"),
    path("grades/", views.GradeView.as_view(), name="list_grade"),
    path("teachers/", views.TeacherView.as_view(), name="list_teacher"),
    path("home-works/", views.HomeWrokView.as_view(), name="list_homework"),
    # DETAILS
    path(
        "student/<pk>/detail/",
        views.RollDetailView.as_view(),
        name="detail_student",
    ),
    path(
        "course/<pk>/detail/",
        views.CourseDetailView.as_view(),
        name="detail_course",
    ),
    path(
        "subject/<pk>/detail/",
        views.SubjectDetailView.as_view(),
        name="detail_subject",
    ),
    path(
        "section/<pk>/detail/",
        views.SectionDetailView.as_view(),
        name="detail_section",
    ),
    path(
        "class/<pk>/detail/",
        views.ClassroomDetailView.as_view(),
        name="detail_classroom",
    ),
    path(
        "teacher/<pk>/detail/",
        views.TeacherDetailView.as_view(),
        name="detail_teacher",
    ),
    path(
        "grade/<pk>/detail/",
        views.GradeDetailView.as_view(),
        name="detail_grade",
    ),
    path(
        "home-work/<pk>/detail/",
        views.HomeWrokDetailView.as_view(),
        name="detail_homework",
    ),
    # CREATE
    path("add/student/", views.RollCreateView.as_view(), name="add_student"),
    path(
        "add/teacher/", views.TeacherCreateView.as_view(), name="add_teacher"
    ),
    path("add/course/", views.CourseCreateView.as_view(), name="add_course"),
    path("add/grade/", views.GradeCreateView.as_view(), name="add_grade"),
    path(
        "add/section/", views.SectionCreateView.as_view(), name="add_section"
    ),
    path(
        "add/subject/", views.SubjectCreateView.as_view(), name="add_subject"
    ),
    path(
        "add/classroom/",
        views.ClassroomCreateView.as_view(),
        name="add_classroom",
    ),
    path(
        "add/home-work/",
        views.HomeWorkCreateView.as_view(),
        name="add_home_work",
    ),
    # UPDATE
    path(
        "edit/student/<pk>/",
        views.RollUpdateView.as_view(),
        name="edit_student",
    ),
    path(
        "edit/teacher/<pk>/",
        views.TeacherUpdateView.as_view(),
        name="edit_teacher",
    ),
]

sms/views.py
from django.contrib import messages
from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    FormView,
    ListView,
    UpdateView,
)

from sms.forms import (
    ClassroomForm,
    CourseForm,
    GetClassForm,
    GetCourseForm,
    GetGradeForm,
    GetStudentForm,
    GetSubjectForm,
    GetTeacherForm,
    GradeForm,
    HomeWorkForm,
    SectionForm,
    StudentRegistrationForm,
    SubjectForm,
    TeacherRegistrationForm,
)
from users.forms import StudentForm, TeacherForm, UserRegistrationForm
from users.models import Profile, Student, Teacher

from . import utils
from .models import (
    Classroom,
    Course,
    Grade,
    HomeWork,
    Parent,
    Roll,
    Section,
    Subject,
    TeacherContract,
)


# ROLLS
# Permissions (only teachers and staff)
class RollView(ListView):
    template_name = "sms/list.html"
    model = Roll
    context_object_name = "students"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Filter by classroom
        context["form"] = GetStudentForm()
        classroom = self.request.GET.get("classroom")
        if classroom:
            context["students"] = Roll.objects.filter(classroom=classroom)
        return context


class RollDetailView(DetailView):
    template_name = "sms/details.html"
    model = Roll
    context_object_name = "student"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        subject = self.request.GET.get("subject", None)
        context["student"] = {
            "roll": self.object,
            "grades": utils.format_grades(
                course=self.object.course,
                student=self.object.student,
                subject=subject,
            ),
        }
        context["form"] = GetGradeForm(self.request.user)
        return context


# Only staff
class RollCreateView(FormView):
    template_name = "sms/forms.html"
    form_class = StudentRegistrationForm
    model = Roll
    success_url = reverse_lazy("sms:dashboard")

    @transaction.atomic
    def form_valid(self, form):
        data = form.cleaned_data
        sid = Student.objects.count() + 1
        s_data = {
            "username": f"1003{sid}",
            "password1": f"1003{sid}@2024",
            "password2": f"1003{sid}@2024",
            "role": "STUDENT",
        }

        # Create student
        s_form = StudentForm(data=s_data)
        student = s_form.save()
        utils.add_user_to_group(student)

        profile = Profile(user=student)
        for key, value in data.items():
            setattr(profile, key, value)
        profile.save()

        role = form.save(commit=False)
        role.student = student
        role.save()

        # Create parent
        if form.data["parent_name"]:
            pid = Parent.objects.count() + 1
            p_data = {
                "username": f"3003{pid}",
                "password1": f"3003{pid}@2024",
                "password2": f"3003{pid}@2024",
                "role": "PARENT",
            }

            p_form = UserRegistrationForm(data=p_data)
            parent = p_form.save()
            _parent = Parent.objects.create(
                user=parent,
                full_name=data["parent_name"],
                address=data["address"],
                phone_no=data["parent_phone_no"],
            )
            _parent.student.add(student)

        return super().form_valid(form)


class RollUpdateView(UpdateView):
    template_name = "sms/forms.html"
    form_class = StudentRegistrationForm
    model = Roll
    success_url = reverse_lazy("sms:dashboard")

    def get_initial(self):
        profile = self.get_object().student.profile
        initial_data = super().get_initial()

        initial_data["first_name"] = profile.first_name
        initial_data["last_name"] = profile.last_name
        initial_data["date_of_birth"] = profile.dob
        initial_data["phone_no"] = profile.phone_no
        initial_data["parent_phone_no"] = profile.parent_phone_no
        initial_data["parent_address"] = profile.parent_address
        initial_data["parent_name"] = profile.parent_name
        initial_data["address"] = profile.address
        return initial_data

    def form_valid(self, form):
        data = form.cleaned_data

        roll = form.save()

        profile = Profile.objects.get(user=roll.student)
        for key, value in data.items():
            setattr(profile, key, value)
        profile.save()

        return super().form_valid(form)


# TEACHER
# Only staff
class TeacherView(ListView):
    template_name = "sms/list.html"
    model = TeacherContract
    context_object_name = "teachers"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = GetTeacherForm(self.request.user or None)
        class_id = self.request.GET.get("classroom")
        subject_id = self.request.GET.get("subject")
        status = self.request.GET.get("status")
        query = None

        if not status:
            return context

        if class_id == "" and subject_id == "":
            query = TeacherContract.objects.filter(
                status=status,
            )
        elif class_id == "" and subject_id != "":
            query = TeacherContract.objects.filter(
                subject__id=subject_id,
                status=status,
            )
        elif class_id != "" and subject_id == "":
            query = TeacherContract.objects.filter(
                classroom__id=class_id,
                status=status,
            )

        else:
            query = TeacherContract.objects.filter(
                classroom__id=class_id,
                subject__id=subject_id,
                status=status,
            )

        if not query:
            messages.info(self.request, "No record found!")
            query = self.object_list

        context["teachers"] = query
        return context


class TeacherDetailView(DetailView):
    template_name = "sms/details.html"
    model = TeacherContract
    context_object_name = "teacher"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# Only Staff
class TeacherCreateView(FormView):
    template_name = "sms/forms.html"
    model = TeacherContract
    form_class = TeacherRegistrationForm
    success_url = reverse_lazy("sms:list_teacher")

    @transaction.atomic
    def form_valid(self, form):
        __id = Teacher.objects.count() + 1
        data = {
            "username": f"2003{__id}",
            "password1": f"2003{__id}@2024",
            "password2": f"2003{__id}@2024",
            "role": "TEACHER",
        }
        t_form = TeacherForm(data=data)
        teacher = t_form.save()
        utils.add_user_to_group(teacher)

        profile = Profile(user=teacher)
        for key, value in form.cleaned_data.items():
            setattr(profile, key, value)
        profile.save()

        contract = form.save(commit=False)
        contract.teacher = teacher
        contract.save()

        return super().form_valid(form)


class TeacherUpdateView(UpdateView):
    template_name = "sms/forms.html"
    model = TeacherContract
    form_class = TeacherRegistrationForm
    success_url = reverse_lazy("sms:list_teacher")

    def get_initial(self):
        initial_data = super().get_initial()
        contract = self.get_object()
        teacher = contract.teacher
        initial_data["first_name"] = teacher.profile.first_name
        initial_data["last_name"] = teacher.profile.last_name
        initial_data["date_of_birth"] = teacher.profile.dob
        initial_data["phone_no"] = teacher.profile.phone_no
        initial_data["address"] = teacher.profile.address
        initial_data["category"] = contract.category
        initial_data["classroom"] = contract.classroom.all()
        initial_data["subject"] = contract.subject.all()
        initial_data["status"] = contract.status
        initial_data["date_start"] = contract.date_start

        return initial_data

    def form_valid(self, form):
        data = form.cleaned_data
        contract = self.get_object()
        profile = Profile.objects.get(user=contract.teacher)

        for key, value in data.items():
            setattr(profile, key, value)
        profile.save()
        return super().form_valid(form)


# COURSE
class CourseView(ListView):
    template_name = "sms/list.html"
    model = Course
    context_object_name = "courses"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Filter by course name
        context["form"] = GetCourseForm
        course = self.request.GET.get("course")
        if course:
            context["courses"] = Course.objects.filter(name=course)

        return context


class CourseDetailView(DetailView):
    template_name = "sms/details.html"
    model = Course
    context_object_name = "course"


class CourseCreateView(CreateView):
    template_name = "sms/forms.html"
    model = Course
    form_class = CourseForm
    success_url = reverse_lazy("sms:add_course")


# SUBJECT
class SubjectView(ListView):
    model = Subject
    template_name = "sms/list.html"
    context_object_name = "subjects"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Filter by course
        context["form"] = GetSubjectForm
        cid = self.request.GET.get("course")
        if cid:
            context["subjects"] = Subject.objects.filter(course=cid)

        return context


class SubjectDetailView(DetailView):
    model = Subject
    template_name = "sms/details.html"
    context_object_name = "subject"


class SubjectCreateView(CreateView):
    model = Subject
    template_name = "sms/forms.html"
    form_class = SubjectForm

sms/templates/sms/partials/classroom_detail.html
<div>
  <h1>{{classroom.name}}</h1>
  <table>
    <thead>
      <tr>
        <th>Code ID</th>
        <th>Student Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for roll in classroom.rolls.all %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_student' pk=roll.pk %}">{{roll.student.username}}</a>
        </td>
        <td>
          {{roll.student.profile.first_name}} {{roll.student.profile.last_name}}
        </td>
        <td>
          <a href="#">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/classrooms.html
<div>
  <form>
    {{form}}
    <button>submit</button>
  </form>
  <table>
    <caption>
      List Classrooms
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Course</th>
        <th>Year</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for classroom in classrooms %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_classroom' pk=classroom.pk %}"
            >{{classroom.pk}}</a
          >
        </td>
        <td>{{classroom.name}}</td>
        <td>{{classroom.course}}</td>
        <td>{{classroom.year}}</td>
        <td>
          <a href="#">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/course_detail.html
<h1>{{course.name}}</h1>
<p><b>Date Create: </b>{{course.year}}</p>

<!--CLASSESS-->
<div>
  <table>
    <caption>
      Classess
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Year</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for class in course.classrooms.all %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_classroom' pk=class.pk %}">{{class.pk}}</a>
        </td>
        <td>{{class.name}}</td>
        <td>{{class.year}}</td>
        <td>
          <a href="#">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<!--SUBJECTS-->
<div>
  <table>
    <caption>
      Subjects
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Section</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for subject in course.subjects.all %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_subject' pk=subject.pk %}">{{subject.pk}}</a>
        </td>
        <td>{{subject.name}}</td>
        <td>{{subject.section}}</td>
        <td>
          <a href="#">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/courses.html
<h1>List Courses</h1>

<div>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Year</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for course in courses %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_course' pk=course.pk %}">{{course.pk}}</a>
        </td>
        <td>{{course.name}}</td>
        <td>{{course.year}}</td>
        <td>
          <a href="#">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/grade_detail.html
<h1>Detail Grade</h1>

<div>
  <table>
    <thead>
      <tr>
        <th>STUDENT</th>
        <th>ACS 1</th>
        <th>ACS 2</th>
        <th>MACS</th>
        <th>ACP</th>
        <th>ACS 1</th>
        <th>ACS 2</th>
        <th>MACS</th>
        <th>ACP</th>
        <th>ACS 1</th>
        <th>ACS 2</th>
        <th>MACS</th>
        <th>ACP</th>
        <th>MT-A</th>
        <th>MT-B</th>
        <th>MT-C</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <a href="{% url 'sms:detail_student' pk=grade.student.pk %}">{{grade.student}}</a>
        </td>
        {% if grade.a %}
        <td>{{grade.a.test_1}}</td>
        <td>{{grade.a.test_2}}</td>
        <td>{{grade.a.test_average}}</td>
        <td>{{grade.a.exam}}</td>
        {% endif %} {% if grade.b %}
        <td>{{grade.b.test_1}}</td>
        <td>{{grade.b.test_2}}</td>
        <td>{{grade.b.test_average}}</td>
        <td>{{grade.b.exam}}</td>
        {% endif %} {% if grade.c %}
        <td>{{grade.c.test_1}}</td>
        <td>{{grade.c.test_2}}</td>
        <td>{{grade.c.test_average}}</td>
        <td>{{grade.c.exam}}</td>
        <td>{{grade.a.section_average}}</td>
        <td>{{grade.b.section_average}}</td>
        <td>{{grade.c.section_average}}</td>
        {% endif %}
      </tr>
    </tbody>
  </table>
</div>

sms/templates/sms/partials/homework_detail.html
<h1>{{homework.topic}}</h1>
<p>
  Teacher:
  <a href="{% url 'sms:detail_teacher' pk=homework.teacher.pk %}">{{homework.teacher}}</a>
</p>
<p>Date Create: {{homework.date_create}}</p>
<p>Date Close: {{homework.date_create}}</p>
<div>{{homework.content}}</div>

sms/templates/sms/partials/sections.html
<form method="get">
  {{form}}
  <button>get</button>
</form>
<div>
  <table>
    <caption>
      List Sections
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for section in sections %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_section' pk=section.pk %}">{{section.pk}}</a>
        </td>
        <td>{{section.name}}</td>
        <td>
          <a href="#">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/sidebar.html
<aside>
  <ul>
    <li><a href="{% url 'sms:dashboard' %}">Dashboard</a></li>
    <li><a href="{% url 'sms:list_course' %}">Courses</a></li>
    <li><a href="{% url 'sms:list_classroom' %}">Classrooms</a></li>
    <li><a href="{% url 'sms:list_section' %}">Sections</a></li>
    <li><a href="{% url 'sms:list_subject' %}">Subjects</a></li>
    <li><a href="{% url 'sms:list_student' %}">Students</a></li>
    <li><a href="{% url 'sms:list_teacher' %}">Teachers</a></li>
    <li><a href="{% url 'sms:list_grade' %}">Grades</a></li>
  </ul>
</aside>

sms/templates/sms/partials/student_detail.html
<h1>
  {{student.roll.student.profile.first_name}}
  {{student.roll.student.profile.last_name}}
</h1>
<p><b>Date of Birth: </b>{{student.roll.student.profile.dob}}</p>
<p><b>Phone No: </b>{{student.roll.student.profile.phone_no}}</p>
<p>
  <b>Parent: </b><a href="">{{student.roll.student.parents.first.full_name}}</a>
</p>
<p>
  <b>Parent Phone No: </b><a href="tel:{{student.roll.student.profile.parent_phone_no}}">
    {{student.roll.student.profile.parent_phone_no}}
  </a>
</p>
<address>
  <p><b>Student Address: </b>{{student.roll.student.profile.address}}</p>
  <p><b>Parent Address: </b>{{student.roll.student.profile.parent_address}}</p>
</address>
<br />
<p><b>Code: </b>{{student.roll.student.username}}</p>
<p><b>Course: </b>{{student.roll.course}}</p>
<p><b>Classroom: </b>{{student.roll.classroom}}</p>
<p><b>Date Join: </b>{{student.roll.year}}</p>

<div>
  <form method="get">
    {{form.subject}}
    <button>submit</button>
  </form>
  <table>
    <caption>
      Grades
    </caption>
    <thead>
      <tr>
        <th>Subject</th>
        <th>ACS 1</th>
        <th>ACS 2</th>
        <th>MACS</th>
        <th>ACP</th>
        <th>ACS 1</th>
        <th>ACS 2</th>
        <th>MACS</th>
        <th>ACP</th>
        <th>ACS 1</th>
        <th>ACS 2</th>
        <th>MACS</th>
        <th>ACP</th>
        <th>MT-A</th>
        <th>MT-B</th>
        <th>MT-C</th>
      </tr>
    </thead>
    <tbody>
      {% for g in student.grades %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_subject' pk=g.subject.pk %}">{{g.subject}}</a>
        </td>
        <td>{{g.a.test_1}}</td>
        <td>{{g.a.test_2}}</td>
        <td>{{g.a.test_average}}</td>
        <td>{{g.a.exam}}</td>
        <td>{{g.b.test_1}}</td>
        <td>{{g.b.test_2}}</td>
        <td>{{g.b.test_average}}</td>
        <td>{{g.b.exam}}</td>
        <td>{{g.c.test_1}}</td>
        <td>{{g.c.test_2}}</td>
        <td>{{g.c.test_average}}</td>
        <td>{{g.c.exam}}</td>
        <td>{{g.a.section_average}}</td>
        <td>{{g.b.section_average}}</td>
        <td>{{g.c.section_average}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/students.html
<form>
  {{form}}
  <button>submit</button>
</form>
<div>
  <table>
    <caption>
      List Students
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Full Name</th>
        <th>Course</th>
        <th>Classroom</th>
        <th>Year</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_student' pk=student.pk %}">{{student}}</a>
        </td>
        <td>
          {{student.student.profile.first_name}}
          {{student.student.profile.last_name}}
        </td>
        <td>{{student.course}}</td>
        <td>{{student.classroom}}</td>
        <td>{{student.year}}</td>
        <td>
          <a href="{% url 'sms:edit_student' pk=student.pk%}">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/subject_detail.html
<h1>{{subject.name}}</h1>

<p><b>Date Add: </b>{{subject.year}}</p>
<h2>Courses</h2>
<hr />
<ul>
  {% for course in subject.course.all %}
  <li>
    <a href="{% url 'sms:detail_course' pk=course.pk %}">{{course}}</a>
  </li>
  {% endfor %}
</ul>
<h2>Sections</h2>
<hr />
<ul>
  {% for section in subject.section.all %}
  <li>
    <a href="{% url 'sms:detail_section' pk=section.pk %}">{{section}}</a>
  </li>
  {% endfor %}
</ul>
<h2>Teachers</h2>
<hr />
<ul>
  {% for teacher in subject.teacher.all %}
  <li>
    <a href="{% url 'sms:detail_teacher' pk=teacher.pk %}">{{teacher}}</a>
  </li>
  {% endfor %}
</ul>

sms/templates/sms/partials/subjects.html
<form method="get">
  {{form}}
  <button>get</button>
</form>
<div>
  <table>
    <caption>
      List Subjects
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Date Added</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for subject in subjects %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_subject' pk=subject.pk %}">{{subject.pk}}</a>
        </td>
        <td>{{subject.name}}</td>
        <td>{{subject.year}}</td>
        <td>{{subject.status}}</td>
        <td>
          <a href="#">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

sms/templates/sms/partials/teacher_detail.html
<h1>
  {{teacher.teacher.profile.first_name}} {{teacher.teacher.profile.last_name}}
</h1>

<p><b>Phone No: </b>{{teacher.teacher.profile.phone_no}}</p>
<p><b>Address: </b>{{teacher.teacher.profile.address}}</p>
<p><b>Code: </b>{{teacher.teacher.username}}</p>
<p><b>Date Celebrate: </b>{{teacher.date_celebrate}}</p>
<p><b>Date Start: </b>{{teacher.date_start}}</p>
<p><b>Status: </b>{{teacher.status}}</p>
<p><b>Class: </b>{{teacher.category}}</p>
<h2>Subjects</h2>
<hr />
<ul>
  {% for subject in teacher.subject.all %}
  <li>
    <a href="{% url 'sms:detail_subject' pk=subject.pk %}">{{subject}}</a>
  </li>
  {% endfor %}
</ul>
<h2>Classrooms</h2>
<hr />
<ul>
  {% for classroom in teacher.classroom.all %}
  <li>
    <a href="{% url 'sms:detail_classroom' pk=classroom.pk %}">{{classroom}}</a>
  </li>
  {% endfor %}
</ul>

sms/templates/sms/partials/teachers.html
<form method="get">
  {{form}}
  <button>get</button>
</form>
<div>
  <table>
    <caption>
      List Teachers
    </caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Category</th>
        <th>Date Celebrate</th>
        <th>Date Start</th>
        <th>Status</th>
        <th>Date Close</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for teacher in teachers %}
      <tr>
        <td>
          <a href="{% url 'sms:detail_teacher' pk=teacher.pk %}">{{teacher.pk}}</a>
        </td>
        <td>{{teacher.teacher.profile.first_name}}</td>
        <td>{{teacher.teacher.profile.last_name}}</td>
        <td>{{teacher.category}}</td>
        <td>{{teacher.date_celebrate}}</td>
        <td>{{teacher.date_start}}</td>
        <td>{{teacher.status}}</td>
        <td>{{teacher.date_end}}</td>
        <td>
          <a href="{% url 'sms:edit_teacher' pk=teacher.pk %}">Edit</a>
          <a href="#">Del</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>